I18n.ur =
  menu:
    schema: "خاکہ"
    new: "نیا۔۔۔"
    load: "کھولیں۔۔۔"
    save: "محفوظ کریں"
    save_as: "کاپی محفوظ کریں"
    templates: "سانچہ۔۔۔"
    properties: "خاصیتیں۔۔۔"
    share: "بانٹیں۔۔۔"
    import: "درآمد کریں"
    edit: "ترمیم"
    undo: "واپس کریں"
    redo: "دوبارہ کریں"
    insert: "ڈالیں"
    table: "ٹیبل"
    note: "اشارة"
    view: "دیکحیں"
    show_minimap: "چھوٹا نقشہ دیکھائیں"
    hide_minimap: "چھوٹا نقشہ چھپائیں"
    show_sidebar: "سائیڈ بار دیکھائیں"
    hide_sidebar: "سائیڈ بار چھپائیں"
    sort_items: "اشیا کی ترتیب"
    linetype: "لکیر کی قسم"
    bezier: "گولائی"
    cornered: "کنارے دار"
    options: "اختیارات۔۔۔"
    export: "برآمد"
    sql: "ایس قیو ایل۔۔۔"
    image: "تصویر۔۔۔"
    help: "مدد"
    index: "ہندوی"
    changes: "تبدیلیاں"
    shortcuts: "کی بورڈ شارٹ کٹ"
    feedback: "رائے"
    about: "بارے"
    guest: "مہمان"
    login: "کلمہ عبور"
    logout: "خروج"
    settings: "تَراکیب"
  panel:
    history: "History"
    last_versions_label: "اس سکیما کے آخری ۱۰ ورژن"
    properties: "خاصیتیں"
    properties_schema_name: "خاکہ کا نام:"
    properties_database: "ڈیتا بیس:"
    comments: "رائے"
    comment_placeholder: "اپمی رائے یہاں تحریر کریں"
    send: "بھیج دیں"
  dialog:
    new_schema: "نیا خاکہ"
    new_schema_title: "عنوان"
    new_schema_database: "ڈیتا بیس"
    new_schema_type_info: """Selecting the "generic" database type will allow you to generate SQL for all the databases; but you will only have access to the generic datatypes."""
    new_schema_create_new: "نیا خاکہ بنائیں"
    load_schema: "پرانا خاکہ کھولیں"
    load_schema_your_schemas: "آپ کے خاکے"
    load_schema_schema_name: "خاکے کا نام"
    load_schema_database: "ڈیتا بیس"
    load_schema_last_save: "Last Save"
    load_schema_shared_with_you: "آپ کے ساتھ بانٹے ہوئے خاکے:"
    load_schema_owner: "مالک"
    load_schema_no_schemas: "آپ نے کوئی خاکہ محفوظ نہیں کیا"
    load_schema_no_shared_schemas: "آپ کے ساتھ کوئی خاکہ نہیں بانٹا گیا"
    saveas: "کاپی محفوظ کریں"
    saveas_title: "عنوان"
    saveas_button: "کاپی محفوظ کریں"
    templates: "سانچے"
    templates_schema_name: "خاکہ کا نام"
    templates_database: "ڈیتا بیس"
    templates_description: "حلیہ"
    properties: "خاکہ کی خاصیتیں"
    properties_title: "عنوان"
    properties_publish: "سانچہ کے طور پر تحشیر"
    properties_template_info: ")سانچے ہر استعمال کرنے والے کو دکھائی دیں گے("
    properties_delete_schema: "خاکہ حظف کریں"
    properties_delete_alert: "(You will permanently delete this schema and all associated comments)"
    properties_save: "تبدیلیاں محفوظ کریں"
    share: "بانٹیں"
    share_info: "آپ اپنا خاکہ ۵ لوگوں کو بانٹ سکتے ہیں"
    share_email: "E-mail"
    share_access: "Access"
    share_read_only: "Read only"
    share_read_write: "Read and write"
    share_send_email: "Send invitation e-mail"
    share_invite_button: "مدوع کریں"
    share_collaborators: "Collaborators:"
    import: "Import Sql"
    login_email: "E-mail"
    login_password: "Password"
    login_button: "Login"
    login_forgot_password: "میں اپنا کلمہ عبور بھول چکا ہوں"
    options: "Options"
    options_line_colors: "لکیر کا رنگ"
    options_invert_line_direction: "لکیر کی سپت پلٹیں"
    options_show_fk_icon: "Show Foreign Key Icon"
    options_show_not_null_icon: "Show Not Null icon"
    options_show_default_values: "Show Default Values"
    options_language: "زبان"
    options_save_changes: "تبدیلیاں محفوظ کریں"
    export_sql: "Export SQL"
    export_sql_generate: "Generate SQL"
    export_sql_download: "Download SQL file"
    export_image: "Export Image"
    export_image_zoomin: "Zoom in"
    export_image_zoomout: "Zoom out"
    export_image_reset: "Reset"
    export_image_open_in_new_tab: "Open image in new tab"
    help: "مدد"
    shortcuts: "Keyboard Shortcuts"
    help_changelog: "تبدیلیاں"
    feedback: "رائے"
    feedback_type: "رائے کی قسم"
    feedback_bug: "Bug report"
    feedback_feature: "Feature Request"
    feedback_help: "مدد"
    feedback_other: "متفرق"
    feedback_message: "پیغام"
    feedback_button: "اپنی رائے بھیجیں"
    about: "بارے  dbdesigner.net"
    user_settings: "User Settings"
    user_settings_username: "کلمہ عبور"
    user_settings_email: "E-mail"
    user_settings_save: "تبدیلیاں محفوظ کریں"
    login: "دخول"
    close: "بند کریں"
  designer:
    save_note_edit: "محفوظ کریں"
    cancel_note_edit: "Cancel"
    delete_note: "حذف کریں"
    table_save: "محفوظ کریں"
    table_cancel: "Cancel"
    table_delete: "Delete Table"
    table_add_field: "Add field"
    field_name: "نام"
    field_type: "قسم"
    field_size: "جسامت"
    field_default: "قدرتی"
    field_allow_nulls: "Allow nulls"
    field_primary_key: "Primary Key"
    field_foreign_key: "Foreign Key"
    field_save: "محفوظ کریں"
    field_update: "اپڈیٹ کریں"
    field_cancel: "Cancel"
    field_delete: "فیلڈ حزف کریں"
    field_delete_alert: "Are you sure you want to delete this field?\n(hold shift to delete without confirmation)"
    field_ref_table: "Ref. Table"
    field_ref_field: "Ref. Field"
  alerts:
    delete_schema: "کیا آپ واقعی اس خاکہ کو حظف کرنا چاہتے ہیں؟"
    server_error: "سرور پر کچھ مسلہ آ گیا ہے"
    schema_owner_error: "Only the schema owner can change share settings"
    login_to_use_this_function: "You should login to use this function"